### PR TITLE
Fix panic when parsing malformed array input

### PR DESCRIPTION
**Pull request by cbandy**
Noticed one possible out-of-bounds when reviewing 80f8150043c80fb52dee6bc863a709cdac7ec8f8. Found and verified the others with go-fuzz.

### CODE REVIEW

**Comment by freeformz** [comment]
👍 . Ignore the Go1.4 failures for now, goimports doesn't work with go1.4 anymore.

**Comment by AidHamza** [comment]
👍

**Comment by freeformz** [comment]
@cbandy Can you rebase?

**Comment by cbandy** [comment]
Rebased.

**Pull request merged**
