### PR TITLE
Add support for SCRAM-SHA-256 authentication.

### PR DESCRIPTION
**Pull request by hlinnaka**
Upcoming PostgreSQL version 10 adds SCRAM-SHA-256 authentication. Implement
it in the driver.

This includes a built-in implementation of SASLPrep.

### CODE REVIEW

**Comment by johto** [comment]
1 commit with 1,337 additions and 0 deletions 🤔

Slightly surprised how much code went into this (considering how much cryptography Go has in its standard library), but it looks like a lot of it is just magic tables.

I can review this work this weekend, but I'd appreciate if someone else did that as well.

**Comment by cbandy** [comment]
I'll devote _some_ time this weekend as well, though probably not enough for a complete review.

I'm not sure if/how we should consider external dependencies. A quick search pointed me to the following:
 - https://github.com/golang/go/issues/16257
 - https://godoc.org/golang.org/x/text/secure/precis

So I have an idea of how to approach this, @hlinnaka, is this a port of some other implementation?

**Comment by hlinnaka** [comment]
On 05/05/2017 10:35 PM, Chris Bandy wrote:
> I'll devote _some_ time this weekend as well, though probably not enough for a complete review.

Thanks!

> I'm not sure if/how we should consider external dependencies. A quick search pointed me to the following:
>  - https://github.com/golang/go/issues/16257
>  - https://godoc.org/golang.org/x/text/secure/precis
>
> So I have an idea of how to approach this, @hlinnaka, is this a port of some other implementation?

Ah, I saw issue #16257 earlier, when I googled around, but I didn't 
notice there was a SCRAM-SHA-256 implementation included in that. 
Looking at that implementation, it doesn't do SASLprep (yet). Could 
improve that, of course.

I'm OK with using that implementation, although it seems like it's still 
in early stages. I bet it will still change a lot until it becomes 
stable. SCRAM is simple enough that it wouldn't save much in terms of 
lines of code. My guess would be that having the extra dependency would 
outweight the benefits, but this is the first time I dabble into Go, I'm 
not sure how much trouble that is in practice.

I ported the SASLprep code from the implementation in upstream 
PostgreSQL libpq library, see 
https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/common/saslprep.c;hb=HEAD. 
The rest I wrote from scratch. (I wrote that upstream SASLprep 
implementation, too.)

PRECIS isn't identical to SASLprep, although it's close. I'm not sure 
what exactly the differences are.

- Heikki

**Comment by johto** [comment]
My health unfortunately won't let me spend any time on this this weekend.  I'll try and organize some time some other weekend, but I can't promise anything.

**Comment by SamWhited** [comment]
> Ah, I saw issue #16257 earlier, when I googled around, but I didn't notice there was a SCRAM-SHA-256 implementation included in that.

Fair warning: my library doesn't support the server side of SASL yet and the API is probably going to have to undergo at least one breaking change to add that. API feedback and thoughts would be welcomed.

> Looking at that implementation, it doesn't do SASLprep (yet).

This is trivial to add, I just didn't have an [RFC 7613](https://tools.ietf.org/html/rfc7613) implementation yet when I started on the SASL implementation. The credentials API probably also will be part of the change when adding server support though. Having it as an option doesn't make a lot of sense since credentials may be just about anything, not just usernames and passwords.

> PRECIS isn't identical to SASLprep, although it's close. I'm not sure what exactly the differences are. 

PRECIS attempted to be as backwards compatible as possible and, in the particular case of SASLprep, most likely won't cause any problems as long as you re-normalize your data. See: [RFC 7613 §6](https://tools.ietf.org/html/rfc7613#section-6)

**Comment by lafriks** [comment]
Any update on this?

**Comment by evitalis** [comment]
Also curious on updates as they are needed for continued usage of Gitea.

**Comment by williambanks** [comment]
Any chance of an ETA on merging this PR?

**Comment by onemanstartup** [comment]
Any progress?

**Comment by dnp1** [comment]
Also interested on this. How can I help this to be merged?

**Comment by mjibson** [comment]
I haven't done a review of the PR, but at a minimum it needs a test that connects to a real postgres server using this method. My read of the tests suggests this is missing.

**Comment by niski84** [comment]
my team really needs this feature.  Can anyone help get this merged?

**Comment by niski84** [comment]
Hi, we very much need this feature for our Sept release. Is there any possible way to get this test case working so we can get this feature from last year merged?

**Comment by mjibson** [comment]
This also needs a rebase onto master.

**Comment by Neustradamus** [comment]
Any news about it?

**Comment by ptman** [comment]
maybe the tests could be used for the merged scram auth?

**Comment by knz** [comment]
This PR has been superseded by #833 and can be closed.

**Pull request closed without merging**
