### PR TITLE
pgpass implementation #75

### PR DESCRIPTION
**Pull request by fazalmajid**
#75 Implementation of the .pgpass mechanism http://www.postgresql.org/docs/9.4/static/libpq-pgpass.html

### CODE REVIEW

**Comment by mattn** [comment]
Any update on this?

**Comment by fazalmajid** [comment]
Well, it's ready, it works and passes the tests and the pull request is submitted. It looks like there are a quite a few open pull requests that haven't been reviewed or merged either.

**Comment by mattn** [comment]
@fazalmajid yes, I know it's ready. But stil not reviewed and merged. had passed  three months already.

**Comment by uhoh-itsmaciek** [comment]
Sorry about that. I think this is reasonable. I'll merge it tomorrow if there are no objections. Thanks for submitting the patch.

**Comment by mattn** [comment]
@uhoh-itsmaciek Good to hear. Best regards.

**Comment by freeformz** [comment]
I would ask that the docs at least get a small update mentioning that this lib also supports .pgpass.

**Comment by uhoh-itsmaciek** [comment]
@freeformz good point; I'll do that unless you'd like to update the PR @fazalmajid.

**Comment by fazalmajid** [comment]
@uhoh-itsmaciek
Please go ahead, I don't know the documentation standards, and I'd rather not trigger another round of Travis CI (it seems fairly inconsistent and throws false positives).

All it should really be is a cross-reference to http://www.postgresql.org/docs/current/static/libpq-pgpass.html and a note that the Windows mechanism is not yet implemented.

**Comment by uhoh-itsmaciek** [comment]
I've rebased, added a brief doc blurb, and added you to the contributors list [here](https://github.com/lib/pq/compare/pgpass). If this looks good I'll merge it.

**Comment by fazalmajid** [comment]
@uhoh-itsmaciek: seems fine to me, thanks

**Comment by uhoh-itsmaciek** [comment]
Merged. Thanks for the patch, and sorry about the delay.

**Comment by mattn** [comment]
:tada:

**Pull request closed without merging**
