### PR TITLE
Use `net.{Join,Split}HostPort` for proper ipv6 handling

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by cbandy** [comment]
:thumbsup:

**Comment by tamird** [comment]
Travis failure is unrelated, see https://github.com/lib/pq/pull/399.

**Comment by tamird** [comment]
@johto this is green. Would you mind taking a look?

**Comment by uhoh-itsmaciek** [comment]
Thanks for the patch!

**Pull request merged**
