### PR TITLE
implement additional context specific sql interfaces

### PR DESCRIPTION
**Pull request by kylejbrock**

### CODE REVIEW

**Comment by basvanbeek** [comment]
Currently context methods on Conn are provided in the conn_go18.go file. I think it's best if you move these stmt context methods there too. 

A next PR could potentially merge the conn*.go files as it seems minimum required version for lib/pq is Go 1.9.

**Comment by kylejbrock** [comment]
@basvanbeek Are there any additional changes you'd like to see?

**Comment by twpayne** [comment]
Any update on this? I tried to use a prepared COPY IN statement inside a context-aware transaction. When the context is canceled, `github.com/lib/pq` deadlocks (there's a race condition found by the Go race detector). The underlying reason seems to be that `github.com/lib/pq` doesn't have this PR merged :)

Code to reproduce the race condition is [here](https://gist.github.com/twpayne/f8e448f69944dbec1f05e2d3d7b3cd39).

**Comment by prksu** [comment]
any update? i hope this PR to be merged

**Comment by jalan** [comment]
Is there anything blocking this change?

It is surprising behavior that contexts are supported properly when using `DB.ExecContext` but not when using `Stmt.ExecContext`.

**Comment by kylebrock** [comment]
🤷

**Comment by KillerX** [comment]
I mean, I understand that the maintainers do not owe us anything, but it would sure be nice to hear back if we can do anything to get this merged!

It appears that there are several "forks" popping up mostly for the purpose of merging this patch, so it's somewhat splitting up the users, which seems like a bad idea...

**Comment by mjibson** [comment]
I didn't really read it over in detail. Someone tell me if it breaks anything.

**Comment by kjbass** [comment]
This breaks things


```
# github.com/lib/pq
../../lib/pq/conn_go18.go:213:21: not enough arguments in call to st.cn.cancel
	have ()
	want (context.Context)
```

**Comment by kjbass** [comment]
Above snippet is the output of executing `go get github.com/lib/pq`

**Comment by mjibson** [comment]
Thanks. Reverted.

**Comment by kylejbrock** [comment]
This PR was from 1.5 yrs ago.  Give me a second and I'll updated it.

**Comment by mjibson** [comment]
I didn't realize I hadn't re-run the CI tests which have changed a lot since then. Thanks for getting another one together.

**Comment by kylejbrock** [comment]
@mjibson It's been a really long time since I've thought about any of this.

But, here is a PR that compiles: https://github.com/lib/pq/pull/921

**Pull request merged**
