### PR TITLE
Add rows.{Result,Tag}() to enable access to the result/tag in queries.

### PR DESCRIPTION
**Pull request by mjibson**
Enable access to the driver result (rows affected) and command
completion tag for statements executed via `conn.Query`.

This can be used in programs that access the connection mechanism directly
instead of through database/sql. CockroachDB is one such example.

### CODE REVIEW

**Comment by cbandy** [comment]
Needs tests. At first glance, I don't think these messages happen for queries that return result sets.

**Comment by mjibson** [comment]
Added tests. Indeed SELECT messages don't produce tags and driver.Results, but if one is, say, running everything the user is sending via .Query because you are processing input from the commandline, then .Result and .Tag become very useful. Again, this is exactly what we are doing in cockroach. Merging this PR would allow us to remove our fork and use the main repo again. The cost to the user is an extra string and int and the time it takes to parse them per rows object.

**Comment by knz** [comment]
LGTM

**Comment by mjibson** [comment]
@tamird mind reviewing this?

**Comment by tamird** [comment]
So the idea is that users of this functionality need to write their own ResultTag interface in order to get at these methods? This feel like feature creep to me - this library doesn't provide many postgres-specific facilities that aren't exposed by database/sql, and I think it's our responsibility to keep it that way.

There are other libraries that do not share this philosophy (such as https://github.com/jackc/pgx) - we should not be making changes to lib/pq that are motivated by our unique development goals in CRDB.

**Comment by mjibson** [comment]
The argument against why this is feature creep is that this feature is useful to any package that needs the data in tag and result. This is not many packages, true, but relying on just database/sql doesn't allow this level of detail about the returned data. Cockroach uses this in its command line package to emulate psql, which prints tags after statements. Any other application attempting to create a command line similar to psql will also need this functionality. So the argument is that this is useful, just to a small group of applications. It is not a cockroach-specific feature (although cockroach is the first to need it).

**Comment by tamird** [comment]
Can you generalize that rationale and include it in the commit message? LG following that.

**Pull request merged**
