### PR TITLE
Fix possible panic on malformed server response

### PR DESCRIPTION
**Pull request by kostya-sh**

### CODE REVIEW

**Comment by johto** [comment]
I'm not sure how I feel about that.  If your server is so broken it sends back invalid responses, would you not want to panic to make sure someone notices?

**Comment by kostya-sh** [comment]
In many (all?) other cases invalid responses do not trigger panics.

**Comment by freeformz** [comment]
FWIW: `errorf` panics. So this doesn't `Fix possible panic` on malformed server responses, it just possibly provides a better panic message?

**Comment by kostya-sh** [comment]
@freeformz, no, this fixes real panic. pq re-panics runtime errors such as bounds out of range: https://github.com/lib/pq/blob/165a3529e799da61ab10faed1fabff3662d6193f/error.go#L482

**Pull request closed without merging**
