### PR TITLE
Support multiple results sets for go 1.8

### PR DESCRIPTION
**Pull request by mjibson**
@kardianos

---
This change is [Reviewable](https://reviewable.io/reviews/lib/pq/532)

### CODE REVIEW

**Comment by tamird** [comment]
Consider adding 1.8 or tip to .travis with failures allowed. Current code here doesn't compile under 1.8.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[nextresultset_test.go, line 26 at r1](https://reviewable.io:443/reviews/lib/pq/532#-KVZZNnUh07J6XUukfdC:-KVZZNnUh07J6XUukfdD:b-lf3d37) ([raw file](https://github.com/lib/pq/blob/b8a6eaccdc71ba6eb228afaaaf49985a2bd1c9d1/nextresultset_test.go#L26)):*
> ```Go
> 		}
> 	}
> 	if !rows.NextResultSet() {
> ```

HasNextResultSet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lib/pq/532#-:-KVZZVE5WJ_PVj1p_U0k:bin9cnh)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[nextresultset_test.go, line 26 at r1](https://reviewable.io:443/reviews/lib/pq/532#-KVZZNnUh07J6XUukfdC:-KVZ_VgP15Q-jO4ehc3l:be5tcad) ([raw file](https://github.com/lib/pq/blob/b8a6eaccdc71ba6eb228afaaaf49985a2bd1c9d1/nextresultset_test.go#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> HasNextResultSet
</details>
Rather, `HasNextResultSet` should be removed - the methods implemented on `*rows` appear to be incorrect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lib/pq/532)*

**Comment by mjibson** [comment]
Yes, it does compile under 1.8. See "TestMultiple" which only appears in the travis tip builds: https://travis-ci.org/lib/pq/jobs/172536052

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[nextresultset_test.go, line 26 at r1](https://reviewable.io:443/reviews/lib/pq/532#-KVZZNnUh07J6XUukfdC:-KVa2_LVJXINfPxL3ziy:b-ekyflh) ([raw file](https://github.com/lib/pq/blob/b8a6eaccdc71ba6eb228afaaaf49985a2bd1c9d1/nextresultset_test.go#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Rather, `HasNextResultSet` should be removed - the methods implemented on `*rows` appear to be incorrect.
</details>
No, this is correct. That method is only available to the driver, not on a rows. See https://tip.golang.org/pkg/database/sql/#Rows.NextResultSet and https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit from which this code was taken from.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lib/pq/532#-:-KVa2njSdBk72GNAH7W2:bemsv9f)*

**Comment by mjibson** [comment]
Renamed the test file because it may be used for the other 1.8 features. Added tests to ensure that extra, unused results don't change future results.

**Comment by freeformz** [comment]
Please don't use reviewable.

**Comment by tamird** [comment]
Ah, I was under the misapprehension that the database/sql.Rows was an interface, but it is not. LGTM

**Comment by itsjamie** [comment]
Simply marking this as related to #531

**Pull request merged**
