### PR TITLE
Remove unnecessary allocation

### PR DESCRIPTION
**Pull request by tamird**
Submitting on behalf of @petermattis.

This commit is extracted from #425.

@johto

### CODE REVIEW

**Comment by tamird** [comment]
This is green.

**Comment by freeformz** [comment]
Doesn't this loose the Columns and other data on queries which return an empty data set ?

**Comment by tamird** [comment]
@freeformz what do you mean? `st` never has anything useful initialized on it; there is no functional change here, except for saving an allocation.

**Comment by freeformz** [comment]
You are totally correct. My bad.

**Comment by johto** [comment]
LGTM, pushed in fde2b33cb1c820fbd3ff19eb9414be2d86b1bd12.  Thanks!

**Pull request closed without merging**
