### PR TITLE
Add support for testing against 9.5

### PR DESCRIPTION
**Pull request by freeformz**

### CODE REVIEW

**Comment by johto** [comment]
Is there a reason not to test with PQTEST_BINARY_PARAMETERS=no?

**Comment by freeformz** [comment]
@johto Nope, added.

**Comment by uhoh-itsmaciek** [comment]
So... looks good, but weird Travis failures. I restarted the two builds that failed, but at least one of them seemed to crash Postgres, which isn't great. I tried to repro locally, but I can't can't `gvm` to work correctly...

**Comment by freeformz** [comment]
I also restarted one (unrelated) and it just worked. This is my experience though with the test suite as a whole. I haven't looked into it more though. @uhoh-itsmaciek I'm going to merge this unless there are any objections.

**Pull request merged**
