### PR TITLE
Issue494

### PR DESCRIPTION
**Pull request by mjibson**

### CODE REVIEW

**Comment by mjibson** [comment]
I ran this with the original tests in cockroach that found the bug and they now pass without complaining about a data race. I think it's time to clean this up and get it merged.

**Comment by freeformz** [comment]
Fixes #494

**Comment by freeformz** [comment]
Done.

**Comment by tamird** [comment]
We should add `go test -race` to travis while you're fixing this.

**Comment by mjibson** [comment]
```
--- FAIL: TestCopyRespLoopConnectionError (0.02s)
	copy_test.go:410: expected *pq.Error or driver.ErrBadConn, got &net.OpError{Op:"write", Net:"tcp", Source:(*net.TCPAddr)(0xc4201a7e60), Addr:(*net.TCPAddr)(0xc4201a7e90), Err:(*os.SyscallError)(0xc42021f740)}
```

One of the test failures occurred on go Tip, postgres 9.5. It appears to not always happen, so we may have some flaky tests.

**Comment by freeformz** [comment]
Adding `go test -race` should be done separately IMO.

**Pull request merged**
