### PR TITLE
Scan naive dates as UTC, matching stdlib

### LINKED ISSUE #329: PG types without timezone being parsed into time.Times with.
Hi,

I briefly discussed this with @johto in `#postgresql`.

Currently, when a time-based PG type that doesn't have timezone information is parsed into a Go type, it's parsed into a `time.Time` that does contain timezone information. Specifically, the resulting `time.Time` contains a single `zone` in the `Location`, while the zero-value for a `time.Location` would contain an empty slice of `zones`, i.e., the absence of any timezones.

Given the `PG` value `'2015-01-13'::date` it should be equivalent to the following `time.Time`:

```go
time.Time{
        sec: 63556704000, 
        nsec: 0, 
        // zero value for a *time.Location
        loc: &time.Location{
                name: "", 
                zone: []time.zone(nil), 
                tx: []time.zoneTrans(nil), 
                cacheStart: 0, 
                cacheEnd: 0, 
                cacheZone: (*time.zone)(nil),
         },
}
```

Currently, `lib/pq` would return the following `time.Time`:

```go
time.Time{
    sec: 63556704000, 
    nsec: 0, 
    loc: &time.Location{
        name: "", 
        zone: []time.zone{
            time.zone{
                name: "", 
                offset: 0, 
                isDST: false,
            },
        }, 
        tx: []time.zoneTrans{
            time.zoneTrans{
                when: -9223372036854775808, 
                index: 0x0, 
                isstd: false, 
                isutc: false},
            },
        },
        cacheStart: -9223372036854775808, 
        cacheEnd: 9223372036854775807, 
        cacheZone:(*time.zone)(0xc20801eaa0),
    },
}
```

I'm don't think this is correct because the `time.Location` produced by `lib/pq` contains zone information, even if the zone is itself the zero-value.

I would be happy to put a fix in for this, but wanted to see if there was support for that idea or not?  I've added a PR with a test case highlighting the issue.

### PR DESCRIPTION
**Pull request by akshayjshah**
When scanned into a `time.Time`, we currently assign temporal types without timezone information a `time.Location` of `time.FixedLocation("", 0)` (i.e., an unnamed location with zero offset from UTC). This PR changes behavior to use `time.UTC` instead.

This change is desirable because it makes our behavior match the standard library's `time` package, which typically uses `time.FixedLocation` only when there _is_ an explicit offset provided. When there's no timezone data, the standard library assumes UTC. (See [time.Parse](https://pkg.go.dev/time?tab=doc#Parse) for an example.)

This change shouldn't be too disruptive to well-behaved client code. The returned `time.Time` structs still represent the same instant in time, and they're equivalent when compared using [`time.Equal`](https://pkg.go.dev/time?tab=doc#Time.Equal). The discussion on #329 includes many people using `reflect.DeepEqual` to compare `time.Time`s, but that should have become _much_ less common after the [introduction of monotonic time in 2017](https://go.googlesource.com/proposal/+/master/design/12914-monotonic.md), the addition of `time.Equal`, and the slow spread of `github.com/google/go-cmp/cmp` in tests.

This PR fixes #329 and supersedes the now-ancient #328. I pulled in @e-dard's commit, so he should still get credit for filing the initial issue and adding a failing test case.

cc @stgarrity, who's also interested

### CODE REVIEW

**Comment by akshayjshah** [comment]
The failing test looks like it may be related to the race described in #563. Perhaps @mjibson or another maintainer can re-run the failing portion of the build?

**Comment by amenzhinsky** [comment]
I'm sorry but this doesn't solve the problem, the default timezone should fallback to the local timezone not UTC, plus it can be easily controlled with `TZ` env var.

For example querying a database with a default timezone, say +10 with `SELECT NOW()::timestamp` results in the same timestamp but with UTC or +0 tz now, local time in go app would be +20 already.

**Comment by amenzhinsky** [comment]
```
# select now();
              now
-------------------------------
 2020-06-16 17:36:56.045896+03
```

Ends up `2020-06-16 17:36:56.045896 +0000 +0000` in go when it should be `+3`.

**Comment by johto** [comment]
> I'm sorry but this doesn't solve the problem, the default timezone should fallback to the local timezone not UTC, plus it can be easily controlled with `TZ` env var.

That's just one opinion.  If we don't know what the time zone is, any guess we do is going to be incorrect for some people.  Go chooses to guess UTC, postgres uses the `TimeZone` setting.

> For example querying a database with a default timezone, say +10 with `SELECT NOW()::timestamp` results in the same timestamp but with UTC or +0 tz now, local time in go app would be +20 already.

So don't do that.

**Comment by amenzhinsky** [comment]
> That's just one opinion. If we don't know what the time zone is, any guess we do is going to be incorrect for some people. Go chooses to guess UTC, postgres uses the `TimeZone` setting.

What I'm saying is that all apps should default to the system timezone, that's what initdb does, `TimeZone` is an optional setting

**Comment by johto** [comment]
> What I'm saying is that all apps should default to the system timezone, that's what initdb does, `TimeZone` is an optional setting

You should tell that to [Go](https://golang.org/pkg/time/#Parse) then as well:

> In the absence of a time zone indicator, Parse returns a time in UTC.

**Comment by akshayjshah** [comment]
@amenzhinsky, there's already a long-ish discussion of this behavior on #329. Let's keep discussion of the desired behavior on that thread, so it benefits from context. Discussion here would be more helpful if it focused on this PR's *implementation* of the desired behavior.

If you don't have a chance to read all of #328, the most relevant portion is @johto's comment from 2015:

>> I think we should use the session time zone.

> No, that would be a huge backwards compatibility breakage.

**Comment by akshayjshah** [comment]
Seems like this isn't going anywhere; I'm closing this to get it off my list of open PRs.

**Pull request closed without merging**
